syntax = "proto3";

package task;

option go_package = "grpc-basics/proto";

// --- Messages ---

message Task {
    int32  id          = 1;
    string description = 2;
    bool   completed   = 3;
    string created_at  = 4;
    string completed_at = 5;
}

message CreateTaskRequest {
    string description = 1;
}

message CreateTaskResponse {
    Task task = 1;
}

message GetTaskRequest {
    int32 id = 1;
}

message GetTaskResponse {
    Task task = 1;
}

message ListTasksRequest {}

message ListTasksResponse {
    repeated Task tasks = 1;  // repeated = slice
}

message CompleteTaskRequest {
  int32 id = 1;
}

message CompleteTaskResponse {
    Task task = 1;
}

// --- Service ---

service TaskService {
    rpc CreateTask (CreateTaskRequest) returns (CreateTaskResponse);
    rpc GetTask    (GetTaskRequest)    returns (GetTaskResponse);
    rpc ListTasks  (ListTasksRequest)  returns (ListTasksResponse);
    rpc CompleteTask (CompleteTaskRequest) returns (CompleteTaskResponse);
}