name: Deploy Task API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Run tests
        run: go test ./...

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o task-api-linux ./week2

      - name: Copy Files via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "task-api-linux"
          target: "/home/ec2-user/"

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl restart task-api
            sudo systemctl status task-api --no-pager