name: Deploy Task API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: taskdb_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d taskdb_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      
      - name: Initialize test database
        working-directory: ./week2/task-api
        run: |
          PGPASSWORD=postgres psql -h localhost -p 5433 -U postgres -d taskdb_test -f schema.sql  

      - name: Run tests
        working-directory: ./week2/task-api
        run: go test ./...

      - name: Build Linux binary
        working-directory: ./week2/task-api
        run: |
          GOOS=linux GOARCH=amd64 go build -o task-api-linux .

      - name: Copy Files via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "week2/task-api/task-api-linux"
          target: "/home/ec2-user/"

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl restart task-api
            sudo systemctl status task-api --no-pager